export const FETCHING_POSTS_DATA = 'FETCHING_POSTS_DATA'
export const FETCHED_POSTS_DATA = 'FETCHED_POSTS_DATA'

export const FETCHING_AUTHORS_DATA = 'FETCHING_AUTHORS_DATA'
export const FETCHED_AUTHORS_DATA = 'FETCHED_AUTHORS_DATA'

export const ROUTE_CHANGED = 'ROUTE_CHANGED'
